# -*- coding: utf-8 -*-
"""Exp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOS9mYmh5LqpIT_xeyozkwW2DZkqShk3
"""

q1="1.Program to find the best of two test average marks out of three using total - min"
print(q1)

# Accepting marks from the user
test1 = float(input("Enter marks for Test 1: "))
test2 = float(input("Enter marks for Test 2: "))
test3 = float(input("Enter marks for Test 3: "))

# Calculate total and find minimum
total = test1 + test2 + test3
lowest = min(test1, test2, test3)

# Calculate average of best two tests
average = (total - lowest) / 2

# Display result
print(f"The average of the best two test marks is: {average}")

"""Result : the program is executed successfully

"""