# -*- coding: utf-8 -*-
"""Exp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BROs6YxW8-dUdPEkJoruYzP1VvvaizK
"""

Q2="2. develop a python program to check whether a given number is palindrome or not and also count the number of occurrences of each digit in the input number"
print(Q2)
number = input("Enter a number: ")

if number == number[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")

for i in range(10):
    count = number.count(str(i))
    if count > 0:
        print(f"{i} appears {count} times")