# -*- coding: utf-8 -*-
"""Exp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hcN0sDAcfWhJ5_MGyQnFvo15ueRL4Fp1
"""

Q3="""3. Fibonacci sequence: Defined as a function F as Fn = Fn-1 + Fn-2. Write a Python program which accepts a value for N (where N >0) as input and pass this value to the function. Display suitable error message if the condition for input value is not followed """
print(Q3)

def fibonacci_sequence(N):
    if N <= 0:
        print("Error: N must be greater than 0.")
        return
    fib_list = []
    a, b = 0, 1
    for _ in range(N):
        fib_list.append(a)
        a, b = b, a + b
    print("Fibonacci sequence up to", N, "terms:", fib_list)

try:
    N = int(input("Enter the number of terms (N > 0): "))
    fibonacci_sequence(N)
except ValueError:
    print("Error: Please enter a valid integer.")

"""Result :the program is executed successfully

"""