# -*- coding: utf-8 -*-
"""Exp4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2OkzRX4_EhuN1-iZ3A-xn_U1Xw57VqU
"""

Q4="""Binary to Decimal & Octal to Hexadecimal Conversion: Develop a python program to convert binary to decimal, octal to hexadecimal using functions. """
print(Q4)

def binary_to_decimal(binary_str):
    # Convert binary string to decimal integer
    return int(binary_str, 2)

def octal_to_hexadecimal(octal_str):
    # Convert octal string to decimal integer, then to hexadecimal (uppercase, without '0x')
    return hex(int(octal_str, 8))[2:].upper()

# Input from user
binary = input("Enter a binary number: ")
octal = input("Enter an octal number: ")
# Function calls and output
print("Decimal value of binary:", binary_to_decimal(binary))
print("Hexadecimal value of octal:", octal_to_hexadecimal(octal))

"""Result:the program is executed successfully

"""