# -*- coding: utf-8 -*-
"""Exp5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSbCoyjThJYSZoKR3RqxqKx7Z9GpefEY
"""

Q5=""" 5. Sentence Statistics: Write a Python program that accepts a sentence and find the number of words, digits, uppercase letters and lowercase letters. """
print(Q5)

sentence = input("Enter a sentence: ")

# Count words
words = sentence.split()
num_words = len(words)

# Initialize counters
num_digits = 0
num_uppercase = 0
num_lowercase = 0

# Count digits and letters
for char in sentence:
    if char.isdigit():
        num_digits += 1
    elif char.isupper():
        num_uppercase += 1
    elif char.islower():
        num_lowercase += 1

print("Number of words:", num_words)
print("Number of digits:", num_digits)
print("Number of uppercase letters:", num_uppercase)
print("Number of lowercase letters:", num_lowercase)

"""REsult : the program is executed successfully

"""