# -*- coding: utf-8 -*-
"""Exp7a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10OmUx3qB9l09RafWXgA___FrTwd_LHSp
"""

Q7a="7.a. Write a python program to implement insertion sort using lists."
print(Q7a)

def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key

# Example usage:
nums = [8, 7, 13, 1, -9, 4]
insertion_sort(nums)
print("Insertion sort result:", nums)

"""Result : the program is executed successfully

"""